#
# Module manifest for module 'DbaTuning'
#
# Generated by: Mitchell Hamann 
#
# Generated on: 8/15/2017
#
@{
	
	# Script module or binary module file associated with this manifest.
	RootModule = 'dbatuning.psm1'
	
	# Version number of this module.
	ModuleVersion = '0.0.100'
	
	# ID used to uniquely identify this module
	GUID = ''
	
	# Author of this module
	Author = 'Mitchell Hamann'
	
	# Company or vendor of this module
	CompanyName = 'Mitchell Hamann'
	
	# Copyright statement for this module
	Copyright = '2017 Mitchell Hamann'
	
	# Description of the functionality provided by this module
	Description = 'Provides tools to help with database tuning from powershell'
	
	# Minimum version of the Windows PowerShell engine required by this module
	PowerShellVersion = '3.0'
	
	# Name of the Windows PowerShell host required by this module
	PowerShellHostName = ''
	
	# Minimum version of the Windows PowerShell host required by this module
	PowerShellHostVersion = ''
	
	# Minimum version of the .NET Framework required by this module
	DotNetFrameworkVersion = ''
	
	# Minimum version of the common language runtime (CLR) required by this module
	CLRVersion = ''
	
	# Processor architecture (None, X86, Amd64, IA64) required by this module
	ProcessorArchitecture = ''
	
	# Modules that must be imported into the global environment prior to importing this module
	RequiredModules = @()
	
	# Assemblies that must be loaded prior to importing this module
	RequiredAssemblies = @()
	
	# Script files () that are run in the caller's environment prior to importing this module
	ScriptsToProcess = @()
	
	# Type files (xml) to be loaded when importing this module
	TypesToProcess = @()
	
	# Format files (xml) to be loaded when importing this module
	FormatsToProcess = @()
	
	# Modules to import as nested modules of the module specified in ModuleToProcess
	NestedModules = @()
	
	# Functions to export from this module
	FunctionsToExport = @(
		'Connect-TuneSqlInstance'
		,'Connect-DbaSqlServerTest'
		,'Get-TuneLogFiles'
		,'Find-TuneStroredProcedure'
	)
	
	# Cmdlets to export from this module
	CmdletsToExport = '*'
	
	# Variables to export from this module
	VariablesToExport = '*'
	
	# Aliases to export from this module
	# Aliases are stored in azuremanage.psm1
	AliasesToExport = ''
	
	# List of all modules packaged with this module
	ModuleList = @()
	
	# List of all files packaged with this module
	FileList = ''
	
	PrivateData = @{
		# PSData is module packaging and gallery metadata embedded in PrivateData
		# It's for rebuilding PowerShellGet (and PoshCode) NuGet-style packages
		# We had to do this because it's the only place we're allowed to extend the manifest
		# https://connect.microsoft.com/PowerShell/feedback/details/421837
		PSData = @{
			# The primary categorization of this module (from the TechNet Gallery tech tree).
			Category = "sql server"
			
			# Keyword tags to help users find this module via navigations and search.
			Tags = @('dba', 'sql', 'tuning')
			
			# The web address of an icon which can be used in galleries to represent this module
			IconUri = ""
			
			# The web address of this module's project or support homepage.
			ProjectUri = ""
			
			# The web address of this module's license. Points to a page that's embeddable and linkable.
			LicenseUri = "http://www.gnu.org/licenses/gpl-3.0.en.html"
			
			# Release notes for this particular version of the module
			ReleaseNotes = ""
			
			# If true, the LicenseUrl points to an end-user license (not just a source license) which requires the user agreement before use.
			# RequireLicenseAcceptance = ""
			
			# Indicates this is a pre-release/testing version of the module.
			IsPrerelease = 'True'
		}
	}
}